"""Render AGENTS.md.

The generated text lives between two HTML comment markers. Anything a human
writes outside those markers survives regeneration, which is what makes it safe
to wire this into CI.
"""

from __future__ import annotations

from .claims import SECTIONS, VERIFIED

BEGIN = "<!-- verified-init:begin -->"
END = "<!-- verified-init:end -->"

_LEGEND = (
    "_Generated by [verified-init]({url}) v{version}. "
    "No model was consulted: every line below was read from a file in this repository. "
    "Items marked `(inferred)` matched a convention but are declared nowhere — verify them. "
    "Edits inside this block are overwritten on regeneration; "
    "write your own notes outside it._"
)

PROJECT_URL = "https://github.com/mgj96/verified-init"


def render_block(analysis, version: str, title: str = "CLAUDE.md") -> str:
    """The managed block: heading, legend, claims by section, then absences."""
    lines = [BEGIN, "", "# {}".format(title), ""]
    lines.append(_LEGEND.format(url=PROJECT_URL, version=version))
    lines.append("")

    for section in SECTIONS:
        in_section = [c for c in analysis.claims if c.section == section]
        if not in_section:
            continue
        lines.append("## {}".format(section))
        lines.append("")
        for claim in in_section:
            mark = "" if claim.status == VERIFIED else " _(inferred)_"
            lines.append("- {}{}".format(claim.text, mark))
        lines.append("")

    if analysis.probes:
        lines.append("## Not found")
        lines.append("")
        lines.append("These were checked for and are absent. Do not assume they exist:")
        lines.append("")
        for probe in analysis.probes:
            suffix = " - {}".format(probe.why) if probe.why else ""
            lines.append("- `{}`{}".format(probe.looked_for, suffix))
        lines.append("")

    lines.append(END)
    return "\n".join(lines)


def render_agents_md(
    analysis, version: str = "0.0.0", previous=None, title: str = "CLAUDE.md"
) -> str:
    """Full file contents, preserving anything outside the managed block.

    Args:
        analysis: Result of :func:`~verified_init.core.analyze`.
        version: Generator version, recorded in the legend.
        previous: Existing file contents, or ``None`` for a fresh file.
        title: Heading for the generated block; normally the output filename.
    """
    block = render_block(analysis, version, title=title)
    if previous is None:
        return block + "\n"

    start = previous.find(BEGIN)
    stop = previous.find(END)
    if start == -1 or stop == -1 or stop < start:
        # No managed block yet: put ours on top, keep their file underneath.
        return "{}\n\n{}".format(block, previous.lstrip())

    head = previous[:start]
    tail = previous[stop + len(END):]
    return "{}{}{}".format(head, block, tail)
